"""
tools/apps/constants.py
=======================
Defines aliases for common applications and system processes to filter out.
"""

ALIASES: dict[str, str] = {
    # --- Browsers ---
    "chrome":            "chrome",
    "google chrome":     "chrome",
    "firefox":           "firefox",
    "brave":             "brave",
    "edge":              "msedge",
    "microsoft edge":    "msedge",
    "opera":             "opera",

    # --- Dev Tools ---
    "vscode":            "code",
    "vsc":               "code",
    "visual studio code": "code",
    "visual studio":     "devenv",
    "terminal":          "wt",
    "windows terminal":  "wt",
    "cmd":               "cmd",
    "command prompt":    "cmd",
    "powershell":        "powershell",
    "git bash":          '"%ProgramFiles%\\Git\\git-bash.exe"',
    "notepad":           "notepad",
    "notepad++":         "notepad++",
    "sublime":           "subl",
    "sublime text":      "subl",
    "postman":           "postman",
    "docker":            "docker",
    "docker desktop":    '"C:\\Program Files\\Docker\\Docker\\Docker Desktop.exe"',
    "android studio":    "studio64",
    "intellij":          "idea64",
    "pycharm":           "pycharm64",

    # --- Productivity ---
    "explorer":          "explorer",
    "file explorer":     "explorer",
    "files":             "explorer",
    "calculator":        "calc",
    "calc":              "calc",
    "task manager":      "taskmgr",
    "taskmgr":           "taskmgr",
    "snipping tool":     "snippingtool",
    "snip":              "snippingtool",
    "screenshot":        "snippingtool",
    "paint":             "mspaint",
    "word":              "winword",
    "excel":             "excel",
    "powerpoint":        "powerpnt",
    "ppt":               "powerpnt",
    "outlook":           "outlook",
    "onenote":           "onenote",
    "notion":            "start https://notion.so",
    "figma":             "start https://figma.com",
    "canva":             "start https://canva.com",
    "trello":            "start https://trello.com",

    # --- Media ---
    "spotify":           "spotify",
    "spottify":          "spotify",
    "vlc":               "vlc",
    "media player":      "wmplayer",
    "obs":               "obs64",
    "obs studio":        "obs64",
    "audacity":          "audacity",
    "itunes":            "itunes",

    # --- Communication ---
    "discord":           "discord",
    "telegram":          "telegram",
    "tg":                "telegram",
    "whatsapp":          "start https://web.whatsapp.com",
    "wp":                "start https://web.whatsapp.com",
    "teams":             "teams",
    "zoom":              "zoom",
    "slack":             "slack",
    "skype":             "skype",

    # --- Gaming ---
    "steam":             "steam",
    "epic games":        "EpicGamesLauncher",
    "epic":              "EpicGamesLauncher",

    # --- AI / Web shortcuts ---
    "chatgpt":           "start https://chat.openai.com",
    "gpt":               "start https://chat.openai.com",
    "claude":            "start https://claude.ai",
    "gemini":            "start https://gemini.google.com",
    "perplexity":        "start https://perplexity.ai",
    "youtube":           "start https://youtube.com",
    "yt":                "start https://youtube.com",
    "github":            "start https://github.com",
    "google":            "start https://google.com",
    "gmail":             "start https://mail.google.com",
    "drive":             "start https://drive.google.com",
    "twitter":           "start https://x.com",
    "x":                 "start https://x.com",
    "reddit":            "start https://reddit.com",
    "linkedin":          "start https://linkedin.com",
    "netflix":           "start https://netflix.com",
    "amazon":            "start https://amazon.in",
    "flipkart":          "start https://flipkart.com",
    "stackoverflow":     "start https://stackoverflow.com",
    "leetcode":          "start https://leetcode.com",
    "codeforces":        "start https://codeforces.com",

    # --- System ---
    "settings":          "start ms-settings:",
    "control panel":     "control",
    "device manager":    "devmgmt.msc",
    "disk cleanup":      "cleanmgr",
    "defrag":            "dfrgui",
    "system info":       "msinfo32",
    "msconfig":          "msconfig",
    "regedit":           "regedit",
    "services":          "services.msc",
    "event viewer":      "eventvwr.msc",
    "resource monitor":  "resmon",
    "performance":       "perfmon",
}

# System processes to exclude from the running apps list
SYSTEM_PROCESSES = {
    "system", "idle", "registry", "smss.exe", "csrss.exe", "wininit.exe",
    "services.exe", "lsass.exe", "svchost.exe", "dwm.exe", "fontdrvhost.exe",
    "winlogon.exe", "logonui.exe", "spoolsv.exe", "sihost.exe",
    "taskhostw.exe", "ctfmon.exe", "conhost.exe", "runtimebroker.exe",
    "searchhost.exe", "startmenuexperiencehost.exe", "shellexperiencehost.exe",
    "textinputhost.exe", "widgetservice.exe", "securityhealthservice.exe",
    "sgrmbroker.exe", "searchindexer.exe", "searchprotocolhost.exe",
    "searchfilterhost.exe", "audiodg.exe", "igfxcuiservice.exe",
    "nvspcaps64.exe", "nvcontainer.exe", "dashost.exe",
    "smartscreen.exe", "gamebarpresencewriter.exe", "dllhost.exe",
    "wmiprvse.exe", "msiexec.exe", "crashpad_handler.exe",
    "applicationframehost.exe", "systemsettings.exe",
    "windowsinternal.composableshell.experiences.textinput.inputapp.exe",
    "lockapp.exe", "companionapp.exe", "securityhealthsystray.exe",
    "ntoskrnl.exe", "lsaiso.exe", "memory compression", "system interrupts",
    "msmpeng.exe", "nissrv.exe", "mpcmdrun.exe",
    "phoneexperiencehost.exe", "yourphone.exe", "gameinputsvc.exe",
    "gamebarftserver.exe",
}
